// story/numbers-script.js
// The narrative layer for the interactive "Story of Numbers" — a cast of
// characters + a per-scene sequence of dialogue BEATS (bilingual EN/हिं).
// The engine (numbers-interactive.js) plays these beats one at a time in a
// speech bubble; the beat marked `cue:'interact'` is where the hands-on p5
// interaction happens (it unlocks the next beat when ctx.discover() fires).
//
// Kept as data-only (no p5) so the engine file stays focused.

export const CHARACTERS = {
  narrator:   { name: { en: 'Ganita',        hi: 'गणिता'        }, color: '#22D3EE', avatar: '🦉' },
  shepherd:   { name: { en: 'Shepherd',      hi: 'गड़रिया'       }, color: '#FBBF24', avatar: '🧑‍🌾' },
  hunter:     { name: { en: 'Hunter',        hi: 'शिकारी'       }, color: '#34D399', avatar: '🏹' },
  scribe:     { name: { en: 'Scribe',        hi: 'लिपिक'        }, color: '#FBBF24', avatar: '📜' },
  merchant:   { name: { en: 'Roman Merchant',hi: 'रोमन व्यापारी' }, color: '#F87171', avatar: '🧔' },
  apprentice: { name: { en: 'Apprentice',    hi: 'शागिर्द'      }, color: '#A78BFA', avatar: '🧑‍🔧' },
  teacher:    { name: { en: 'Teacher',       hi: 'शिक्षक'        }, color: '#22D3EE', avatar: '👩‍🏫' },
  student:    { name: { en: 'Student',       hi: 'विद्यार्थी'    }, color: '#A78BFA', avatar: '🧑‍🎓' },
  scholar:    { name: { en: 'Indian Scholar',hi: 'भारतीय विद्वान'}, color: '#34D399', avatar: '🧑‍🔬' },
  trader:     { name: { en: 'Trader',        hi: 'सौदागर'       }, color: '#FBBF24', avatar: '🐫' },
  astronomer: { name: { en: 'Astronomer',    hi: 'खगोलशास्त्री'  }, color: '#A78BFA', avatar: '🔭' },
  child:      { name: { en: 'Child',         hi: 'बच्चा'         }, color: '#22D3EE', avatar: '🧒' },
  geometer:   { name: { en: 'Geometer',      hi: 'ज्यामितिज्ञ'   }, color: '#FBBF24', avatar: '📐' },
};

// Shorthand builder for a beat.
const b = (who, en, hi, cue) => ({ who, text: { en, hi }, cue: cue || 'auto' });

export const BEATS = {
  'first-question': [
    b('narrator',
      'Long ago — before writing, before money, before numbers — humans had no way to say how many.',
      'बहुत पहले — लिखाई से पहले, पैसे से पहले, संख्याओं से पहले — इंसान के पास “कितने” कहने का कोई तरीका नहीं था।'),
    b('narrator',
      'But one question would not go away.',
      'पर एक सवाल पीछा नहीं छोड़ता था।'),
    b('narrator',
      'Tap the night sky and place a few stars. Now — without any number word — how would you say how many?',
      'रात के आसमान पर टैप करके कुछ तारे लगाइए। अब — बिना किसी संख्या-शब्द के — आप “कितने” कैसे बताएँगे?',
      'interact'),
    b('narrator',
      'That little itch — “how many?” — is where our whole story begins.',
      'यही छोटी-सी बेचैनी — “कितने?” — हमारी पूरी कहानी की शुरुआत है।'),
  ],

  'shepherd': [
    b('narrator',
      'Meet a shepherd at dawn, leading his flock out to the meadow.',
      'भोर के समय एक गड़रिये से मिलिए, जो अपनी भेड़ों को चरागाह ले जा रहा है।'),
    b('shepherd',
      'Did I bring them all home last night? I cannot even write “twenty”…',
      'क्या मैं कल रात सबको वापस लाया था? मैं तो “बीस” भी नहीं लिख सकता…'),
    b('narrator',
      'So he invents a trick: one sheep, one stone.',
      'तो वह एक तरकीब निकालता है: एक भेड़, एक पत्थर।'),
    b('shepherd',
      'Help me, {name}: click each sheep to send it out — a stone drops for each. Then bring them home.',
      'मेरी मदद कीजिए, {name}: हर भेड़ पर क्लिक करके उसे बाहर भेजिए — हर भेड़ के लिए एक पत्थर गिरेगा। फिर उन्हें वापस बुलाइए।',
      'interact'),
    b('shepherd',
      'A stone is left over — one sheep is missing! The stones never lie.',
      'एक पत्थर बच गया — एक भेड़ खो गई! पत्थर कभी झूठ नहीं बोलते।'),
    b('narrator',
      'One-to-one matching — humanity’s very first step toward number.',
      'एक-से-एक मिलान — संख्या की ओर इंसान का पहला-पहला कदम।'),
  ],

  'body': [
    b('narrator',
      'Before paper, numbers lived on the body — fingers, bones, knotted rope.',
      'कागज़ से पहले, संख्याएँ शरीर में रहती थीं — उँगलियाँ, हड्डियाँ, रस्सी की गाँठें।'),
    b('hunter',
      'One deer today. Two yesterday. Three this week.',
      'आज एक हिरण। कल दो। इस हफ़्ते तीन।'),
    b('narrator',
      'Carve tally marks — click to add them. Watch every fifth mark tie the bundle together.',
      'निशान खींचिए — क्लिक करके जोड़िए। देखिए हर पाँचवाँ निशान गुच्छे को बाँध देता है।',
      'interact'),
    b('narrator',
      'Not numbers yet — just memory, made visible.',
      'अभी संख्याएँ नहीं — बस याददाश्त, जिसे दिखने लायक बना दिया गया।'),
  ],

  'cities': [
    b('narrator',
      'Villages grew into cities. Now people had to count grain, taxes, soldiers.',
      'गाँव शहरों में बदल गए। अब लोगों को अनाज, कर और सैनिक गिनने पड़े।'),
    b('scribe',
      'Twelve goats for the king’s store — record every one in the wet clay.',
      'राजा के भंडार के लिए बारह बकरियाँ — हर एक को गीली मिट्टी में दर्ज करो।'),
    b('scribe',
      'Press a wedge for each goat, until you reach twelve.',
      'हर बकरी के लिए एक निशान दबाइए, जब तक बारह न हो जाएँ।',
      'interact'),
    b('scribe',
      'Phew. Now imagine the king’s six thousand soldiers, one wedge at a time…',
      'उफ़। अब राजा के छह हज़ार सैनिकों को इसी तरह एक-एक करके गिनने की कल्पना कीजिए…'),
    b('narrator',
      'We needed to count faster — and without mistakes.',
      'हमें तेज़ गिनना ज़रूरी था — और बिना गलती के।'),
  ],

  'symbols': [
    b('narrator',
      'Every people made their own symbols. Rome gave us I, V, X, L, C, D, M.',
      'हर सभ्यता ने अपने प्रतीक बनाए। रोम ने दिए I, V, X, L, C, D, M।'),
    b('merchant',
      'Noble letters — fit for an empire!',
      'भव्य अक्षर — किसी साम्राज्य के योग्य!'),
    b('apprentice',
      'But master… how do I multiply them?',
      'पर गुरुजी… इन्हें गुणा कैसे करूँ?'),
    b('merchant',
      '…Carefully.',
      '…सँभलकर।'),
    b('narrator',
      'Slide the number up. Watch a tidy 1944 become the monster MCMXLIV.',
      'संख्या बढ़ाइए। देखिए साफ़-सुथरा 1944 कैसे राक्षस MCMXLIV बन जाता है।',
      'interact'),
    b('narrator',
      'Symbols, yes. But speed? Still missing.',
      'प्रतीक तो थे। पर रफ़्तार? अब भी गायब।'),
  ],

  'place-value': [
    b('narrator',
      'Then came the great secret: a symbol’s value can depend on its place.',
      'फिर आया वह महान रहस्य: किसी प्रतीक का मान उसकी जगह पर निर्भर कर सकता है।'),
    b('teacher',
      'Look carefully — this is 2. This is 20. This is 200.',
      'ध्यान से देखो — यह 2 है। यह 20 है। यह 200 है।'),
    b('student',
      'But… it’s the same symbol!',
      'पर… यह तो वही प्रतीक है!'),
    b('teacher',
      'Yes. Its place changes its power. Drag the digit across the columns.',
      'हाँ। इसकी जगह इसकी ताक़त बदल देती है। अंक को खानों के आर-पार खींचो।',
      'interact'),
    b('narrator',
      'Place value: a few symbols, endless reach.',
      'स्थानीय मान: थोड़े से प्रतीक, असीम पहुँच।'),
  ],

  'nothing': [
    b('narrator',
      'One shadow remained. How do you write a place that is empty?',
      'एक अड़चन बाकी थी। जो जगह खाली हो, उसे कैसे लिखें?'),
    b('narrator',
      'Is “1 _ 5” fifteen… or one hundred and five?',
      '“1 _ 5” पंद्रह है… या एक सौ पाँच?'),
    b('scholar',
      'In India, we gave emptiness a name. It has meaning. It has a place.',
      'भारत में, हमने खालीपन को एक नाम दिया। इसका अर्थ है। इसकी जगह है।'),
    b('scholar',
      'Here, {name} — drag the zero into the empty place, and watch the number become certain.',
      'लीजिए, {name} — शून्य को खींचकर खाली जगह में रखिए, और देखिए संख्या पक्की हो जाती है।',
      'interact'),
    b('scholar',
      'Zero — a mark for nothing, and a tool for everything.',
      'शून्य — ना-कुछ का चिह्न, और हर चीज़ का औज़ार।'),
  ],

  'zero-power': [
    b('narrator',
      'Zero was far more than a placeholder.',
      'शून्य सिर्फ़ जगह भरने वाला नहीं था।'),
    b('student',
      'So this little circle means… nothing?',
      'तो यह छोटा-सा गोला मतलब… कुछ नहीं?'),
    b('scholar',
      'It means nothing. And because of that — it means everything.',
      'इसका मतलब है कुछ नहीं। और इसीलिए — इसका मतलब है सब कुछ।'),
    b('narrator',
      'Pull the zeros out. Watch 105 and 1005 both collapse into 15 — pure chaos.',
      'शून्य हटाइए। देखिए 105 और 1005 दोनों टूटकर 15 बन जाते हैं — पूरी अफ़रा-तफ़री।',
      'interact'),
    b('narrator',
      'With zero, every number keeps its true shape.',
      'शून्य के साथ, हर संख्या अपना सही रूप बनाए रखती है।'),
  ],

  'ten-symbols': [
    b('narrator',
      'Just ten symbols — 0 to 9 — can write any number that exists.',
      'सिर्फ़ दस प्रतीक — 0 से 9 — कोई भी संख्या लिख सकते हैं।'),
    b('trader',
      'The price of wheat, the road between cities…',
      'गेहूँ का दाम, शहरों के बीच की राह…'),
    b('astronomer',
      '…even the movement of the planets.',
      '…यहाँ तक कि ग्रहों की चाल भी।'),
    b('narrator',
      'Spin the wheels — build any number you like.',
      'पहिए घुमाइए — जो चाहें वो संख्या बनाइए।',
      'interact'),
    b('narrator',
      'Born in India, carried by Arab scholars, adopted by the world — the Hindu-Arabic numerals.',
      'भारत में जन्मे, अरब विद्वानों ने आगे पहुँचाए, दुनिया ने अपनाए — हिन्दू-अरबी अंक।'),
  ],

  'beyond': [
    b('narrator',
      'Numbers counted sheep. Then life began to ask harder questions.',
      'संख्याएँ भेड़ें गिनती थीं। फिर ज़िंदगी कठिन सवाल पूछने लगी।'),
    b('merchant',
      'I owe more than I own — how do I write less than nothing?',
      'मुझ पर कमाई से ज़्यादा कर्ज़ है — कुछ नहीं से भी कम कैसे लिखूँ?'),
    b('child',
      'Can one loaf become four equal parts?',
      'क्या एक रोटी चार बराबर हिस्सों में बँट सकती है?'),
    b('geometer',
      'This length is no simple fraction…',
      'यह लंबाई किसी सरल भिन्न में नहीं आती…'),
    b('narrator',
      'Tap each question to grow the number line into a whole new kind of number.',
      'हर सवाल पर टैप कीजिए और संख्या-रेखा को नई तरह की संख्याओं में बढ़ते देखिए।',
      'interact'),
    b('narrator',
      'Reality asked. Numbers always answered.',
      'हक़ीक़त ने पूछा। संख्याओं ने हमेशा जवाब दिया।'),
  ],

  'scales': [
    b('narrator',
      'What began with pebbles became the language of everything.',
      'जो कंकड़ों से शुरू हुआ, वह हर चीज़ की भाषा बन गया।'),
    b('child',
      'One… two… three…',
      'एक… दो… तीन…'),
    b('astronomer',
      'Two and a half million light-years to that galaxy.',
      'उस आकाशगंगा तक पच्चीस लाख प्रकाश-वर्ष।'),
    b('narrator',
      'Drag to zoom out — from a single pebble all the way to a galaxy.',
      'स्लाइडर खींचकर ज़ूम आउट कीजिए — एक कंकड़ से लेकर पूरी आकाशगंगा तक।',
      'interact'),
    b('narrator',
      'The same ten symbols — at every scale of the universe.',
      'वही दस प्रतीक — ब्रह्मांड के हर पैमाने पर।'),
  ],

  'finale': [
    b('narrator',
      'So who invented numbers? Not one person. Not one nation.',
      'तो संख्याएँ किसने बनाईं? न कोई एक व्यक्ति। न कोई एक देश।'),
    b('narrator',
      'Tap each person who shaped the story — light up all six.',
      'कहानी गढ़ने वाले हर व्यक्ति पर टैप कीजिए — छहों को जगमगाइए।',
      'interact'),
    b('narrator',
      'Shepherds, scribes, scholars, children — across thousands of years.',
      'गड़रिये, लिपिक, विद्वान, बच्चे — हज़ारों साल तक।'),
    b('narrator',
      '…and you, {name} — who just walked ten thousand years in a few minutes. The story of numbers is the story of us, learning to hold the world. It all began with: how many?',
      '…और आप, {name} — जो अभी कुछ ही मिनटों में दस हज़ार साल चल आए। संख्याओं की कहानी असल में हमारी कहानी है — दुनिया को थामना सीखते हुए। और यह सब शुरू हुआ: कितने?'),
  ],
};
